# Generated by Django 4.2 on 2025-10-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(max_length=500, upload_to='artworks/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='artworks/thumbnails/%Y/%m/%d/'),
        ),
    ]
