# Generated by Django 4.2 on 2025-11-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_increase_image_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(max_length=500, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='artworks/thumbnails/'),
        ),
    ]
