# Generated by Django 4.2 on 2025-11-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('search_type', models.CharField(choices=[('artwork', 'Artwork'), ('artist', 'Artist'), ('tag', 'Tag'), ('general', 'General')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('dribbble_url', models.URLField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('artwork_created', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('total_shares_received', models.PositiveIntegerField(default=0)),
                ('is_profile_public', models.BooleanField(default=True)),
                ('show_email_publicly', models.BooleanField(default=False)),
                ('allow_messages', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notify_on_like', models.BooleanField(default=True)),
                ('notify_on_share', models.BooleanField(default=True)),
                ('notify_on_follow', models.BooleanField(default=True)),
                ('notify_on_badge', models.BooleanField(default=True)),
                ('notify_on_contest', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme_preference', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20)),
                ('show_activity_status', models.BooleanField(default=True)),
                ('show_artwork_stats', models.BooleanField(default=True)),
                ('show_badges_publicly', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artworks_per_page', models.PositiveIntegerField(default=24)),
                ('default_sort_order', models.CharField(choices=[('newest', 'Newest First'), ('oldest', 'Oldest First'), ('popular', 'Most Popular'), ('views', 'Most Viewed'), ('likes', 'Most Liked')], default='newest', max_length=20)),
                ('hide_nsfw_content', models.BooleanField(default=True)),
                ('hide_ai_generated', models.BooleanField(default=False)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('blocked_tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usersearchhistory',
            index=models.Index(fields=['user', '-created_at'], name='users_users_user_id_19d68e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['level', '-total_xp'], name='users_userp_level_345fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-artwork_created'], name='users_userp_artwork_b43880_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_active'], name='users_userp_last_ac_e19b57_idx'),
        ),
    ]
